In [ ]:
#Numpy Array Operations
#Scenario: You are given a list of daily average temperatures (in degrees Celsius)
#recorded over two weeks. Your task is to use NumPy to analyze this data.

In [ ]:
import numpy as np

In [ ]:
#1. Create a 1D NumPy Array:

#Create a 1D NumPy array named temperatures_w1

temperatures_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])

#display the array
print("week 1 Temperatures:")
print(temperatures_w1)

week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#2. Inspection and Properties:

temperatures_w1 = np.array ([22.5,25.3,20.8,23.4,26.1,24.8,21.9])

#inspect properties
print("shape:", temperatures_w1.shape)
print("datatype:", temperatures_w1.dtype)
print("number of elemnts:", temperatures_w1.size)

shape: (7,)
datatype: float64
number of elemnts: 7


In [ ]:
#3. Array Operations:
#Convert the temperatures_w1 from Celsius to Fahrenheit
#Find the maximum, minimum, and mean temperatures for the week.

temperatures_w1 = np.array ([22.5,25.3,20.8,23.4,26.1,24.8,21.9])

#convert celsius to fahrenheit
temperatures_w1_fahrenheit = (temperatures_w1 * 9/5) + 32

#find the maximum, minimum, and mean temperature
max_temperature = np.max(temperatures_w1_fahrenheit)
min_temperature = np.min(temperatures_w1_fahrenheit)
mean_temperature = np.mean(temperatures_w1_fahrenheit)

#display the results
print("Temperatues in celsius:")
print(temperatures_w1)
print("\nTemperatures in fahrenheit:")
print(temperatures_w1_fahrenheit)

print("\nMaximum temperature:", max_temperature)
print("Minimum temperature:", min_temperature)
print("Mean temperature:", mean_temperature)


Temperatues in celsius:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Temperatures in fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum temperature: 78.98
Minimum temperature: 69.44
Mean temperature: 74.37714285714286


In [ ]:
#4. Array Slicing and Indexing:

temperatures_w1 = np.array ([22.5,25.3,20.8,23.4,26.1,24.8,21.9])

#Extract the temperatures for the first three days of the week.
first_three_days = temperatures_w1[:3]

#Extract the temperatures for the last two days of the week
last_two_days = temperatures_w1[-2:]

#Extract the temperatures for the middle three days of the week.
middle_three_days = temperatures_w1[2:5]

#display the results
print("Temperatures for the first three days:", first_three_days)
print("Temperatures for the last two days:", last_two_days)
print("Temperatures for the middle three days:", middle_three_days)

Temperatures for the first three days: [22.5 25.3 20.8]
Temperatures for the last two days: [24.8 21.9]
Temperatures for the middle three days: [20.8 23.4 26.1]


In [ ]:
#5. Create a 2D Array:
#Create a 2D NumPy array named temperatures

temperatures = np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9], [19.2,22.5,21.3,24.0,23.5,22.8,20.1]])

#display the array
print("2D Temperatures array:")
print(temperatures)



2D Temperatures array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
#6. Inspect and Slice the 2D Array:

temperatures = np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9], [19.2,22.5,21.3,24.0,23.5,22.8,20.1]])

#inspect properties
print("shape:", temperatures.shape)
print("datatype:", temperatures.dtype)
print("number of elements:", temperatures.size)

#extract temperaturesfor each week
week1 = temperatures[0]
week2 = temperatures[1]

#extract weekend temperatures(last two days)for both weeks
weekend_both_weeks = temperatures[:,-2:]

#display the results
print("\ntemperatures for week 1:")
print(week1)

print("\ntemperatures for week 2:")
print(week2)

print("\ntemperatures for the weekend for both weeks:")
print(weekend_both_weeks)

shape: (2, 7)
datatype: float64
number of elements: 14

temperatures for week 1:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

temperatures for week 2:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

temperatures for the weekend for both weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [2]:
import pandas as pd
#Pandas Series:
#1. Creating Pandas Series:
#● Create a Pandas Series named marks with the following data:
#➢ Marks: 95, 92, 89, 85, 80
#➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

marks = pd.Series([95,92,89,85,80],
index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

#display the series
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [6]:
#2. Indexing and Slicing

marks = pd.Series([95,92,89,85,80],
index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

#Use the integer index position to access the mark of the 1st rank student.
print("Marks of 1st rank student:")
print(marks[0])

#Use the loc accessor to retrieve the marks of the top 3 ranks
print("\nMarks of top 3 ranks using loc:")
print(marks.loc[['Rank1','Rank2','Rank3']])

#Use the iloc accessor to retrieve the mark of the 3rd rank student.
print("\nMarks of 3rd rank student using iloc using iloc:")
print(marks.iloc[2])

#Apply a boolean mask to filter:marks are greater than 90.
print("\nRanks with Marks greater than 90:")
print(marks[marks > 90])


Marks of 1st rank student:
95

Marks of top 3 ranks using loc:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

Marks of 3rd rank student using iloc using iloc:
89

Ranks with Marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_937/2476209100.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [7]:
#3. Manipulating Series:

marks = pd.Series([95,92,89,85,80],
index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

#Modify the mark of the student with the 1st rank to 100.
marks.loc['Tank'] = 100
print("After modifying Rank1")
print(marks)

#Remove the entry corresponding to the last rank from the Series.
marks = marks.drop('Rank5')
print("\nAfter removing Rank5")
print(marks)

#Compute the CGPA by dividing each mark in the Series by 10.
cgpa = marks / 10
print("\nCGPA:")
print(cgpa)


After modifying Rank1
Rank1     95
Rank2     92
Rank3     89
Rank4     85
Rank5     80
Tank     100
dtype: int64

After removing Rank5
Rank1     95
Rank2     92
Rank3     89
Rank4     85
Tank     100
dtype: int64

CGPA:
Rank1     9.5
Rank2     9.2
Rank3     8.9
Rank4     8.5
Tank     10.0
dtype: float64


In [9]:
#Pandas DataFrame:
#1. Creating Pandas DataFrame:
#● Create a Pandas DataFrame named transactions with the following data:
#➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
#➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
#'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
#➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
#'South', 'North'
#➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

import pandas as pd

#create dataframe
transactions = pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                             'ProductCategory': ['Electronics', 'Clothing', 'Electronics',
                                                 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                             'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                             'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

#display the Dataframe
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [11]:
#2. Data Exploration:

#create the Dataframe
transactions = pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                             'ProductCategory': ['Electronics', 'Clothing', 'Electronics',
                                                 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                             'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                             'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

#display the dataframe
print("Transactions Dataframe:")
print(transactions)

#head
print("\nHead:")
print(transactions.head())

#tail
print("\nTail:")
print(transactions.tail())

#shape
print("\nshape:")
print(transactions.shape)

#column names
print("\ncolumn names:")
print(transactions.columns)

#datatypes
print("\ndata types:")
print(transactions.dtypes)

#Display only the 'ProductCategory' and 'Amount' columns.
print("\nProduct Category:")
print(transactions[['ProductCategory', 'Amount']])

#Retrieve the last 3 columns of the DataFrame
print("\nLast 3 columns:")
print(transactions.iloc[:, -3:])

#Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
print("\nNorth Region with Amount greater than 200:")
filtered_data = transactions[(transactions['Region'] == 'North') &
                                   (transactions['Amount'] > 200 )]
print(filtered_data)

#value counts for the 'ProductCategory' column.
print("\nProduct Category Value Counts:")
print(transactions['ProductCategory'].value_counts())

 #unique values in the 'Region' column.
print("\nUnique Regions:")
print(transactions['Region'].unique())

 #Group by 'Region' and find the mean amount for each region.
print("\nMean Amount by Regions:")
print(transactions.groupby('Region')['Amount'].mean())

Transactions Dataframe:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7 

In [12]:
#3. Manipulating the DataFrame:

# Create the DataFrame
#create the Dataframe
transactions = pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                             'ProductCategory': ['Electronics', 'Clothing', 'Electronics',
                                                 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
                             'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                             'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

# 1. Modify Amount for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

# 2.Add a new column 'Discount' by calculating 10% of the 'Amount'.
transactions['Discount'] = transactions['Amount'] * 0.10
print("After adding Discount:")
print(transactions)

# 3. Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

print("\nAfter removing TransactionID 109:")
print(transactions)

# 4. Delete the Discount column
transactions = transactions.drop('Discount', axis=1)

print("\nFinal DataFrame:")
print(transactions)


After adding Discount:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

After removing TransactionID 109:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            1